#develop resource to postgres database
datasources:
  default:
    password: posBuddy
    url: jdbc:postgresql://posBuddy.fritz.box:5432/posbuddy

micronaut:
  router:
    static-resources:
      assets:
        paths: file:/tmp/
        mapping: /assets/**
  server:
    cors:
      enabled: true
    port: 8080
    ssl:
      enabled: true
      port: 8443
